### PR TITLE
maintenance, just in case

### PR DESCRIPTION
**Pull request by TacoTheDank**
i know this user has been inactive since April 29, 2016, and that this likely won't ever be merged, but just in case they see this, here are the changes... (i only did this for better performance on my devices tbh, but merge if you feel like it)
- reconfigured project
- reformatted code
- java 1.8 compatibility (and code changes to go with it (lambdas, methods, etc))
- bump acra to 4.6.0RC1 (which actually reduces the apk size, when compared between debug (16KB) and release (12KB) builds using 4.5.0 and 4.6.0RC1)
- changes in layout for better performance

### CODE REVIEW

**Comment by gch1p** [comment]
I lost access to that account and github support refused to help. So yeah, I can't merge that, but thanks anyway. I can fork the repo though and make the fork a new "official" gravitydefied repo, if anyone need that.

**Comment by TacoTheDank** [comment]
i mean, i guess you can do that and make that the new official repo, and then ill make the merge request there

and release it on f-droid again :)  (maybe under a different applicationId)

oh btw here's the apks i built, if you feel like trying them out
[gravitydefied.zip](https://github.com/evgenyzinoviev/gravitydefied/files/2546690/gravitydefied.zip)

**Comment by TacoTheDank** [comment]
@gch1p

**Comment by gch1p** [comment]
sorry for the delay :)
https://github.com/gch1p/gravitydefied

**Comment by TacoTheDank** [comment]
Lol that's fine. Instead of re-pointing the commits, I'll just do them over again, because the apks I built all crash at startup :(

**Comment by TacoTheDank** [comment]
@gch1p Um, could you open up issues, because there's no issues tab under the new repo.

**Pull request closed without merging**
